# Generated by Django 3.0.1 on 2019-12-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=50)),
                ('FileObj', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
