# Generated by Django 3.0.1 on 2019-12-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticobject',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
